name: Test Build Porfio Web App

on:
  push:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Pengecekan Server
      run: echo "Environment siap! Menunggu source code web app di-push ke repositori."
